### PR TITLE
Replace image banner with HTML/CSS version

### PR DESCRIPTION
**Pull request by nightpool**
includes SVG assets for the wires because that would be way too much html markup.

Before and after:
image

### CODE REVIEW

**Comment by nightpool** [comment]
Let me know if you'd prefer the styles go somewhere else, etc. It seemed like a waste to create assets/main.scss just for a handful of styles, and I don't know jekyll well enough to do anything more fancy

**Comment by codementum** [comment]
Nicely done!

**Comment by codementum** [comment]
I went back and added the trailing spaces. They give us newlines in Markdown

**Comment by nightpool** [comment]
@codementum my bad! opened #6 to help add some clarity/self-documentation here

**Pull request merged**
